title: "y=mx+c"
description: "A blog about machine learning and data science written Mihai Nadăș."
author: "Mihai Nadăș"
email: "mihai.nadas@ubbcluj.ro"
  # email: "mihai.nadas@ubbcluj.ro"
show_excerpts: true
theme: minima
minima:
  skin: auto
  social_links:
    github: mihainadas
    x: mihainadas
    linkedin: mihainadas
  header_pages:
    - about.md
    - index.md
google_analytics: G-EHZ4ZE1DV8