title: y=mx+c
description: A blog about machine learning and data science written by an ML PhD Student.
author: Mihai Nadăș
email: mihai.nadas@ubbcluj.ro
show_excerpts: true

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
  - { platform: github, user_url: "https://github.com/mihainadas" }
google_analytics: G-EHZ4ZE1DV8