title: "y=mx+c"
description: "A blog about machine learning and data science written Mihai Nadăș."
author:
  name: "Mihai Nadăș"
  email: "mihai.nadas@ubbcluj.ro"
header_pages:
  - about.md
  - index.md
theme: minima
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/mihainadas"}
    - { platform: x, user_url: "https://x.com/mihainadas"}
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/mihainadas/"}
google_analytics: G-EHZ4ZE1DV8
show_excerpts: true